flags: {}
packages:
- '.'

- location:
    git: git@github.com:ComputationWithBoundedResources/slogic
    commit: 54beea4baf8f2ad1f02d86b4319512b6e70ab4a2
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-core
    commit: 6749fdef9fa092fe04d5e801977f663c656b4f65 
- location:
    git: git@github.com:ComputationWithBoundedResources/tct-common
    commit: b88ce5394cb9a7dde6d3a08a0a15391991e36ed5
extra-deps:
- fgl-visualize-0.1.0.1
- dotgen-0.4.2
resolver: lts-3.4
